config {
    type: "table",
    columns: {
        test: "Place holder for later documentatio",
    }
}

SELECT
  event_date,
  event_timestamp,
  event_name,
  -- user_id, it is always null
  user_pseudo_id,
  user_first_touch_timestamp,
  --platform, it just shows the web value
  -- nested column event params
  (
  SELECT
    ep.value.int_value
  FROM
    UNNEST(event_params) AS ep
  WHERE
    ep.key = 'ga_session_id' ) AS ga_session_id,
  ---- page info
  (
  SELECT
    ep.value.string_value
  FROM
    UNNEST(event_params) AS ep
  WHERE
    ep.key = 'page_location' ) AS page_location,
  (
  SELECT
    ep.value.string_value
  FROM
    UNNEST(event_params) AS ep
  WHERE
    ep.key = 'page_title' ) AS page_title,
  (
  SELECT
    ep.value.int_value
  FROM
    UNNEST(event_params) AS ep
  WHERE
    ep.key = 'percent_scrolled' ) AS percent_scrolled,
  ------------- payment metrics
  (
  SELECT
    ep.value.string_value
  FROM
    UNNEST(event_params) AS ep
  WHERE
    ep.key = 'outbound' ) AS outbound,
  (
  SELECT
    ep.value.string_value
  FROM
    UNNEST(event_params) AS ep
  WHERE
    ep.key = 'transaction_id' ) AS transaction_id,
  (
  SELECT
    ep.value.int_value
  FROM
    UNNEST(event_params) AS ep
  WHERE
    ep.key = 'tax' ) AS tax,
  (
  SELECT
    ep.value.string_value
  FROM
    UNNEST(event_params) AS ep
  WHERE
    ep.key = 'coupon' ) AS coupon,
  ---- revenue & currency is always USD
  user_ltv.revenue AS user_revenue,
  ---- user device information
  device.category AS device_category,
  device.mobile_brand_name AS device_brand,
  device.mobile_model_name AS device_type,
  device.operating_system AS operating_system,
  device.operating_system_version AS operating_system_version,
  device.language AS system_language,
  -- browser info
  device.web_info.browser AS browser,
  device.web_info.browser_version AS browser_version,
-- Geo information
  geo.continent AS continent,
  geo.sub_continent AS sub_continent,
  geo.country AS country,
  geo.region AS region,
  geo.city AS city,

-- Traffic_source fields 
  traffic_source.medium AS traffic_source_medium,
  traffic_source.name AS traffic_source_name,
  traffic_source.source AS traffic_source,

-- nested items
 items.item_id AS item_id,
 items.item_name AS item_name,
 items.item_category AS item_category,
 items.price AS item_price,
 items.item_list_index AS item_list_index,

 -- ingestion data
   "raw_events_2021_jan" AS source_table
FROM
  ${ref("raw_events_2021_jan")},
UNNEST(items) AS items
